services:
  vintage-story:
    image: vintage-story:local
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vs-server
    restart: unless-stopped
    ports:
      - "42420:42420"
    volumes:
      - ./data:/srv/gameserver/data/vs
    environment:
      - TZ=Europe/London  # Set to your timezone
      - VERSION=1.21.0  # Game version - works with release candidates (unstable) as well as regular releases (stable)
    stdin_open: true
    tty: true
